version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Pxlflabao21
      MYSQL_DATABASE: budget
      MYSQL_USER: Kevin
      MYSQL_PASSWORD: Pxlflabao21
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
